# Results
All of the data from the study was included in the results, including outliers such as participants with extremely high reaction times or extremely poor accuracy.


## Reaction Time - Overall vs Congruent vs Incongruent
The overall results including both congruent and incongruent words were analyzed first. The mean reaction time across all trials was about `python mean_rt`. Shown in Figure 1, reaction time decreased sharply between Trial 1 (M = 1.63s) and Trial 2 (M = 1.10s) before evening out in Trial 3 (M = 1.09s). Figure 2 demonstrates the average reaction times of congruent and incongruent words. The mean reaction time for congruent words across all trials was about 1.19 seconds while the mean reaction time for incongruent words across all trials was about 1.28 seconds. Trial 1 went against the hypothesis as the mean reaction time for congruent words (M = 1.63s) was higher than that of incongruent words (M = 1.56s). However, this was not the same for trials 2 and 3. In trial 2, the mean reaction time for congruent words (M = 0.92s) ended up lower than incongruent words (M = 1.16s). Trial 3 followed this same trend with congruent words (M = 1.02) being lower than incongruent words (M = 1.14s). However, unlike the overall results the mean reaction time for congruent words rose slightly from trial 2 to trial 3.


## Accuracy - Overall vs Congruent vs Incongruent
The overall results including both congruent and incongruent words were analyzed first, with the mean accuracy across all trials coming out to about 86.4%. Shown in Figure 3, accuracy in Trial 1 starts off fairly low (M = 81.8%) and rises steadily through Trial 2 (M = 87.5%) and reaches a peak at Trial 3 (M = 90.0%). When compared to the average accuracy based on congruency, the trend shifts away from a steady rise. The mean accuracy for congruent words across all trials was about 92.0%, where incongruent words ended up with a mean accuracy of about 81.3%. Figure 4 demonstrates the mean accuracy based on each trial. Trial 1 started with a large gap between congruent words (M = 91.7%) and incongruent words (M = 76.5%). Despite congruent accuracy remaining higher than incongruent accuracy, Trial 2 saw a drop in congruent accuracy (M = 87.5%) and a rise in incongruent accuracy (M = 82.9%). However, Trial 3 saw a rise in both congruent accuracy (M = 96.9%) and incongruent accuracy (M = 84.6%). Although there was a rise in both congruent and incongruent accuracy, congruent words remained higher than incongruent words through all trials.


## Interaction between congruency and trial on reaction time
In order to analyze the effects of trial and congruency on reaction time, a 2-way repeated measures ANOVA was conducted. Demonstrated in Table 1, the results yielded insignificant effects. There was no significant main effect found of congruency (F(1,15) = 0.200, p = 0.661), meaning there was not a noticeable difference of reaction time between congruent and incongruent conditions. Trial came just short of reaching a significant main effect (F(2,30) = 3.178, p = 0.056). Although trial did not reach statistical significance, this suggests there is a possible trend in reaction time among trials. In addition, the interaction between congruency and trial showed no significance (F(2,30) = 0.280, p = 0.758), meaning there is no significant effect of congruency on reaction time across time. Despite the potential trend of the trial condition, the results of this ANOVA found no significant main effects of congruency on reaction time.


## Interaction between congruency and trial on accuracy
In order to analyze the effect of trial and congruency on accuracy, a 2way repeated measures ANOVA was conducted. Demonstrated in Table 2, similar to the results of the first ANOVA conducted, the results yielded insignificant effects. There was no significant main effect found of congruency (F(1,15) = 2.479, p = 0.136), meaning there was no significant difference of accuracy between congruent and incongruent trials. There was no significant main effect found of trial (F(2,30) = 1.128, p = 0.337), meaning accuracy did not noticeably differ between trials. Unlike the previous ANOVA where trial had a slight trend, this one did not provide a trend of trial. Additionally, the interaction between congruency and trial showed no significance (F(2,30) = 0.488, p = 0.619), meaning there is no significant effect of congruency on accuracy across time. Like the results of the previous ANOVA, there were no significant main effects of congruency on accuracy.


```{python}
import pandas as pd

data = pd.DataFrame({
    "reaction_time": [0.681, 0.524, 0.628, 0.769, 0.599, 0.659, 0.610, 0.675, 0.588, 0.678, 0.545, 0.641, 0.576, 0.561, 0.616, 0.580, 0.670, 0.721, 0.801, 0.572, 0.549, 0.743, 0.534, 0.607, 0.603, 0.561, 1.203, 0.577, 0.562, 0.574, 1.231, 1.144, 1.289, 1.160, 1.278, 1.419, 1.241, 2.117, 1.300, 1.519, 1.179, 1.201, 1.641, 1.209, 1.463, 1.917, 1.089, 1.009, 1.075, 1.258, 1.241, 1.302, 1.187, 1.263, 1.493, 1.171, 1.243, 1.349, 2.632, 5.719, 1.430, 13.240, 2.506, 1.480, 13.747, 1.602, 2.473, 0.864, 4.781, 1.184, 1.185, 3.710, 1.517, 1.431, 1.274, 1.523, 1.145, 1.182, 1.794, 1.066, 1.231, 0.970, 0.740, 0.820, 0.906, 0.775, 0.841, 1.447, 0.716, 0.839, 0.992, 0.549, 1.048, 0.718, 0.726, 1.225, 0.915, 0.761, 0.779, 0.705, 0.703, 0.753, 0.763, 0.796, 0.708, 0.870, 1.080, 0.842, 0.847, 1.066, 0.698, 0.787, 0.689, 0.753, 0.716, 0.822, 0.730, 0.770, 0.835, 1.102, 1.015, 0.920, 1.192, 0.839, 0.717, 1.244, 1.029, 1.358, 1.244, 0.976, 0.894, 0.866, 0.842, 0.831, 0.584, 0.688, 1.370, 0.846, 0.611, 0.645, 0.777, 1.001, 0.756, 0.782, 1.039, 1.008, 0.845, 0.918, 0.764, 0.664, 0.803, 0.839, 0.664, 0.645, 0.831, 0.624, 0.727, 0.684, 0.704, 0.593, 0.557, 0.583, 0.632, 0.603, 0.563, 0.766, 9.214, 0.751, 0.613, 0.643, 1.820, 1.196, 1.316, 1.128, 1.015, 1.010, 0.785, 0.900, 0.712, 0.898, 1.037, 1.427, 0.807, 0.725, 1.742, 0.847, 0.807, 0.925, 0.770, 1.284, 0.932, 1.032, 0.742, 1.179, 0.952, 0.792, 0.835, 0.900, 0.849, 0.810, 0.819, 0.737, 0.685, 0.642, 0.522, 0.543, 0.699, 0.706, 1.548, 0.965, 1.521, 1.206, 1.081, 2.590, 1.021, 0.972, 0.990, 0.856, 0.996, 1.090, 0.922, 0.780, 0.933, 1.015, 1.193, 0.937, 0.817, 0.984, 0.965, 0.862, 0.757, 0.835, 0.759, 0.799, 1.019, 0.768, 1.190, 1.112, 0.937, 0.963, 1.677, 1.377, 1.346, 1.572, 1.425, 1.448, 1.450, 1.309, 1.679, 1.736, 1.175, 0.966, 1.016, 1.118, 1.731, 1.463, 1.233, 1.458, 1.445, 1.135, 1.015, 1.430, 1.540, 0.863, 0.991, 0.784, 1.070, 1.125, 0.968, 1.594, 1.088, 1.069, 0.690, 19.209, 0.988, 0.756, 1.378, 0.922, 0.707, 0.799, 0.762, 0.750, 0.904, 3.663, 0.750, 0.886, 0.595, 0.859, 0.605, 1.037, 0.785, 0.743, 0.690, 0.805, 0.606, 0.603, 0.902, 0.736, 0.624, 0.837, 1.656, 1.607, 1.953, 1.445, 3.871, 1.588, 1.754, 1.168, 1.771, 1.876, 1.014, 1.068, 1.180, 0.967, 1.034, 1.223, 2.154, 3.485, 1.761, 3.024, 1.033, 2.738, 1.085, 1.052, 1.168, 1.092, 1.421, 1.584, 2.055, 1.491, 0.734, 0.843, 0.874, 0.914, 0.945, 0.826, 0.833, 0.782, 0.850, 0.789, 0.737, 0.878, 0.849, 0.777, 0.839, 0.987, 0.853, 0.866, 0.920, 0.758, 0.796, 0.807, 0.728, 0.825, 0.704, 0.842, 0.705, 0.770, 0.758, 1.340, 1.681, 1.149, 1.278, 1.258, 1.391, 0.935, 1.428, 1.039, 0.984, 0.922, 1.211, 1.053, 0.801, 0.854, 1.041, 1.058, 0.912, 1.001, 1.121, 1.018, 1.025, 15.257, 0.936, 0.697, 0.692, 0.899, 0.814, 1.139, 0.928, 1.116, 14.691, 3.276, 0.880, 1.964, 1.139, 1.466, 1.089, 1.024, 1.294, 1.288, 1.008, 1.695, 0.951, 1.016, 1.389, 1.136, 0.932, 1.171, 0.966, 1.368, 1.036, 0.996, 0.822, 0.934, 0.834, 1.292, 0.909, 0.963, 0.991, 1.116, 1.358, 1.409, 1.787, 1.685, 1.220, 1.561, 1.367, 0.711, 1.464, 1.970, 1.108, 1.161, 1.117, 1.229, 1.031, 1.377, 2.021, 1.394, 1.232, 0.595, 0.905, 1.505, 0.858, 0.789, 1.917, 0.686, 0.804, 0.761, 0.733, 1.614, 1.102, 1.099, 0.864, 1.180, 17.071, 0.743, 0.674, 0.535, 0.805, 0.755, 0.705, 2.476, 0.663, 0.549, 0.536, 0.546, 0.757, 0.678, 0.699, 0.543, 2.352, 0.566, 1.946, 0.526, 0.745, 0.658, 0.608, 2.898, 0.514, 0.569]
})

mean_rt = data["reaction_time"].mean()
```
