
```{r}
library(knitr)

rt_table <- data.frame(
  Effect = c("Match vs non-match", "Residual", "Trial", "Residual", "Match vs non-match * Trial", "Residual"),
  `Sum of Squares` = c(0.204, 15.344, 6.035, 28.486, 0.400, 21.441),
  df = c(1, 15, 2, 30, 2, 30),
  `Mean Square` = c(0.204, 1.023, 3.017, 0.950, 0.200, 0.715),
  F = c(0.200, NA, 3.178, NA, 0.280, NA),
  p = c(0.661, NA, 0.056, NA, 0.758, NA)
)

kable(rt_table, align = "c", caption = "Repeated Measures ANOVA, Within Subjects Effects")

```


```{r}
library(knitr)

accuracy_table <- data.frame(
  Effect = c("Match vs non-match", "Residual", "Trial", "Residual", "Match vs non-match * Trial", "Residual"),
  `Sum of Squares` = c(0.275, 1.666, 0.083, 1.099, 0.048, 1.469),
  df = c(1, 15, 2, 30, 2, 30),
  `Mean Square` = c(0.275, 0.111, 0.041, 0.037, 0.024, 0.049),
  F = c(2.479, NA, 1.128, NA, 0.488, NA),
  p = c(0.136, NA, 0.337, NA, 0.619, NA)
)

kable(accuracy_table, align = "c", caption = "Repeated Measures ANOVA, Within Subjects Effects")

```
